### ISSUE TITLE
Unable zu install under Windows

### ISSUE THREAD

**Issue by CobraCalle** [nefiertsrebliS/mqtt-landroid-bridge#2]
Hello,

my whole home automation (including Ip Symcon) ist running under Windows.

If've tried to install the adapter, but when calling npm install I get the following error:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-08-22T07_52_12_313Z-debug-0.log

And this ist the content of the log file:
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\GitHub\mqtt-landroid-bridge-master\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Administrator\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 0ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-08-22T07_55_14_315Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 25ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms
36 timing idealTree:init Completed in 10ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 silly fetch manifest iobroker.worx@github:iobroker-community-adapters/ioBroker.worx
40 silly placeDep ROOT iobroker.worx@ OK for: mqtt-landroid-bridge@1.0.4 want: github:iobroker-community-adapters/ioBroker.worx
41 timing idealTree:#root Completed in 18ms
42 timing idealTree:node_modules/iobroker.worx Completed in 0ms
43 timing idealTree:buildDeps Completed in 20ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 30ms
46 timing command:install Completed in 77ms
47 verbose stack Error: An unknown git error occurred
47 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
47 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
48 verbose cwd D:\GitHub\mqtt-landroid-bridge-master
49 verbose Windows_NT 10.0.17763
50 verbose node v16.17.0
51 verbose npm  v8.15.0
52 error code ENOENT
53 error syscall spawn git
54 error path git
55 error errno -4058
56 error enoent An unknown git error occurred
57 error enoent This is related to npm not being able to find a file.
57 error enoent
58 verbose exit -4058
59 timing npm Completed in 194ms
60 verbose unfinished npm timer reify 1661154914429
61 verbose unfinished npm timer reify:loadTrees 1661154914473
62 verbose code -4058
63 error A complete log of this run can be found in:
63 error     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-08-22T07_55_14_315Z-debug-0.log

Looks like there is some file missing... can anyone help?

Thanks

carl

**Comment by nefiertsrebliS** [comment]
Hi carl,
so far, there are several 100 installations of the bridge. A similar issue has not yet been reported. I myself only use Linux. If you need help from Windows users, please contact the Symcon forum directly. There are some users with Windows experience. Greetings nefiertsrebliS
