### ISSUE TITLE
Import Lib from ioBroker.worx?

### ISSUE THREAD

**Issue by mschlenstedt** [nefiertsrebliS/mqtt-landroid-bridge#4]
Hi,

really great project - I would like to use your MQTT Bridge for Loxone Smarthomes. Would it be possible to reorganize your code so that the code imports the Lib from ioBroker.worx? This way you can focus on the code for the MQTT Bridge but directly import the Lib from ioBroker.worx. As I understood your commits, you always has to check the changes in the ioBroker.worx and include them into your code.

If you import the Lib, you have all the changes and benefits directly without any effort. I kust ask because ioBroker.worx did a lot of changes regarding server blocking problem with the Worx Servers in the latest 2.1.0.

**Comment by nefiertsrebliS** [comment]
You're right. That would be the best way. And that's how my bridge has worked so far. Unfortunately, the ioBroker.worx team has changed the code in such a way that this way no longer works. I don't see a chance at the moment.
