### ISSUE TITLE
Topic is overwritten, no subtopic

### ISSUE THREAD

**Issue by mschlenstedt** [nefiertsrebliS/mqtt-landroid-bridge#5]
Hi,

Thanks for the project! I would like to use the bidge without IP-Symcon but with a Loxone Smarthome system. We use a standard broker (Mosquitto) to connect to Loxone. This works pretty fine, except one problem:

You do not use any subtopics (from my point of view quite uncommon) and use the same topic for the "online" message as well as for the data message. So every time the ping_interval is triggered, the data of the mower is overwritten with "{"online":true}". This makes it useless as the topic message always changes between data and online status.

Online status interval:
https://github.com/nefiertsrebliS/mqtt-landroid-bridge/blob/910ef02ecefd388e23fbb362702eee784742a117/bridge.js#L120

Data message:
https://github.com/nefiertsrebliS/mqtt-landroid-bridge/blob/910ef02ecefd388e23fbb362702eee784742a117/bridge.js#L130

I do not know how ioBroker works, but for all other systems this is not a reliable behaviour and it would be better to use two seperate topics for status and for data, e.g.:

```
device.topic+'/status'
device.topic+'/mowerdata'
```

And from my point of view even better would be a subtopic for the mower serial, so that you have all your mowers in the same toplevel topic:

```
device.topic+'/'+device.sn+'/status'
device.topic+'/'+device.sn+'/mowerdata'
```

I can create a pullrequest if you are interested in the changes.

**Comment by nefiertsrebliS** [comment]
Thank you for your input. If you need the serialnumber in your topic, please simply add it in your topic-line like this:
`"topic": "yourbestmower/serialNumberOfYourMower"`.

**Comment by mschlenstedt** [comment]
Yes, I know IPSym does not need it. In fact you are using blank topics, because you add / to your topic. Looks quite uncommon in all MQTT clients...

My coding does not change the default behaviour with your blank topic, but opens your solution for all other solutions besides IPSym. And it's only a few lines of code...

**Comment by nefiertsrebliS** [comment]
After a successful attempt with subtopics I implemented them without any configuration required. I hope this helps you.

**Comment by mschlenstedt** [comment]
Great!
