### ISSUE TITLE
No Authentication to local broker

### ISSUE THREAD

**Issue by mschlenstedt** [nefiertsrebliS/mqtt-landroid-bridge#6]
Hi,

again: thanks for the project ;-) As written in my other issue I would like to use the bridge without IP-Symcon. Most of the brokers needs authentication. As far as I understood the nodejs mqtt client, you need extra options to add username and password. Currently, the bridge only supports to add the broker url, but no extra options.

If you are interested I would create a pull request for that - fully compatible with the current url options (so existing configs will still work).

**Comment by nefiertsrebliS** [comment]
Thank you for your good contribution. I integrated your idea into my code. Please take a look at the new version.
