### ISSUE TITLE
Login URL for Worx changed

### ISSUE THREAD

**Issue by mschlenstedt** [nefiertsrebliS/mqtt-landroid-bridge#9]
One of my users reported, that the LoginURL for Worx changed from https://id.eu.worx.com to https://id.worx.com:

https://github.com/nefiertsrebliS/mqtt-landroid-bridge/blob/bb3de902527df0ad961494147d15976faa8813e0/worxCloud.js#L54

Reference: https://www.loxforum.com/forum/projektforen/loxberry/plugins/306569-plugin-worx-landroid?p=408076#post408076

**Comment by nefiertsrebliS** [comment]
Thanks for your Information. Update with new URL for Kress and Worx is online.
